Revert "net: bridge: use DEV_STATS_INC()"
This reverts commit ad8d39c7b437fcdab7208a6a56c093d222c008d5.

Log:
../net/bridge/br_forward.c: In function 'deliver_clone':
../net/bridge/br_forward.c:121:17: error: implicit declaration of function 'DEV_STATS_INC' [-Werror=implicit-function-declaration]
  121 |                 DEV_STATS_INC(dev, tx_dropped);
      |                 ^~~~~~~~~~~~~
../net/bridge/br_forward.c:121:36: error: 'tx_dropped' undeclared (first use in this function)
  121 |                 DEV_STATS_INC(dev, tx_dropped);
      |                                    ^~~~~~~~~~
../net/bridge/br_forward.c:121:36: note: each undeclared identifier is reported only once for each function it appears in
  CC      lib/parser.o
  AR      drivers/clk/renesas/built-in.a
../net/bridge/br_forward.c: In function 'maybe_deliver_addr':
  CC      block/blk-mq-virtio.o
../net/bridge/br_forward.c:258:36: error: 'tx_dropped' undeclared (first use in this function)
  258 |                 DEV_STATS_INC(dev, tx_dropped);
      |                                    ^~~~~~~~~~
  CC      techpack/display/msm/dp/dp_pll_5nm.o
  CC      lib/zstd/compress/huf_compress.o
cc1: some warnings being treated as errors
make[3]: *** [../scripts/Makefile.build:274: net/bridge/br_forward.o] Error 1

Fix build.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I11d1805bbb94bbeb78c9b20292c8197da2268b74