feat: fix: add missing function prototypes
Log:
../drivers/nothing_stability/nothing_writeback_kmsg.c:130:5: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  130 | int __verify_target_partition_layout(){
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/nothing_stability/nothing_writeback_kmsg.c:194:22: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  194 | struct block_device *get_target_partition_block_device()
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/nothing_stability/nothing_writeback_kmsg.c:410:5: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  410 | int create_NT_device() {
      |     ^~~~~~~~~~~~~~~~
../drivers/nothing_stability/nothing_writeback_kmsg.c:441:6: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  441 | void remove_NT_device() {
      |      ^~~~~~~~~~~~~~~~
  CC      drivers/mmc/core/sd.o
  CC      drivers/media/dvb-frontends/cxd2880/cxd2880_tnrdmd.o
  CC      net/neuron/channel_bus.o
  CC      techpack/camera/drivers/cam_isp/isp_hw_mgr/isp_hw/sfe_hw/sfe_top/cam_sfe_top.o
  CC      fs/mpage.o
  CC      drivers/misc/aw8697_haptic/haptic_hv.o
  CC      net/neuron/protocol_bus.o
  CC      drivers/gpu/drm/drm_connector.o
cc1: some warnings being treated as errors
make[3]: *** [../scripts/Makefile.build:287: drivers/nothing_stability/nothing_writeback_kmsg.o] Error 1
make[3]: *** Waiting for unfinished jobs....

Change-Id: a5d4b64cbeed8c1b3975caf6e1c8709354d95333
Signed-off-by: TogoFire <togofire@mailfence.com>