scsi: ufs: nuke clear_bit_unlock
- Ref: Revert "Revert "UPSTREAM: scsi: ufs: Avoid busy-waiting by
 eliminating tag conflicts""

log:
../drivers/scsi/ufs/ufshcd.c:2747:31: error: no member named 'lrb_in_use' in 'struct ufs_hba'
 2747 |                 clear_bit_unlock(tag, &hba->lrb_in_use);
      |                                        ~~~  ^

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I6dd48dc4cda53585629879d62df603363efcf063