techpack: audio: Correct symlinks
* These symlinks were meant for the out-of-tree module. Now that we
  build them in-tree, we need to correct them.

Log:
../techpack/audio/soc/pinctrl-wcd.c:19:10: fatal error: 'pinctrl-utils.h' file not found
   19 | #include "pinctrl-utils.h"
      |          ^~~~~~~~~~~~~~~~~
1 error generated.

[TogoFire]: Add log.
Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ic0d144192fe949d0d811b51191435879926bdc1c