Revert "fs: fuse: Drop kiocb_clone function and inherit fs header file"
This reverts commit 064e3af3ad5e60cb346764bd88dd86574db455f5.

This function has now been removed in include/linux/fs.h from OPLUS imports.
Ref: c0f5d003dfd5f04385591655d430a3bd31659ff6 ("fixup! treewide: Import minimal changes from LE2110_11.F.11").

Log:
../fs/fuse/passthrough.c:102:3: error: implicit declaration of function 'kiocb_clone' [-Werror,-Wimplicit-function-declaration]
  102 |                 kiocb_clone(&aio_req->iocb, iocb_fuse, passthrough_filp);
      |                 ^
../fs/fuse/passthrough.c:156:3: error: implicit declaration of function 'kiocb_clone' [-Werror,-Wimplicit-function-declaration]
  156 |                 kiocb_clone(&aio_req->iocb, iocb_fuse, passthrough_filp);
      |                 ^
2 errors generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I9261bc336f1fadbf3d8c526dc6a5287eeb245785