Revert "fix bitmap corruption on close_range() with CLOSE_RANGE_UNSHARE"
This reverts commit e807487a1d5fd5d941f26578ae826ca815dbfcd6.

Log:

../include/linux/bitmap.h:258:30: error: implicit declaration of function 'bitmap_size'; did you mean 'bitmap_fill'? [-Werror=implicit-function-declaration]
  258 |         memset(to + copy, 0, bitmap_size(size) - copy * sizeof(long));
      |                              ^~~~~~~~~~~
      |                              bitmap_fill

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I56d7e11e27fbe8f7f5a4a9e59c2f8da12d1a2102