drivers: oplus_p922x: Resolve return value warnings
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5792:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        copy_from_user(cur_string, buf, len);
        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5793:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(cur_string, 0, &cur);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5894:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        copy_to_user(buf, vol_string, len);
        ^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5911:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        copy_from_user(vol_string, buf, len);
        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5912:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(vol_string, 0, &vol);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:5991:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(buffer, 0, &val);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~
  CC      drivers/tty/serial/earlycon.o
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:6355:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(buffer, 0, &val);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:6527:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        copy_from_user(string, buf, count);
        ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:6529:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(string, 0, &freq);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:6672:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(buffer, 0, &pmw_pulse);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
drivers/power/oplus/v1/wireless_ic/oplus_p922x.c:6775:2: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
        kstrtoint(buffer, 0, &idt_adc_cmd);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~
11 errors generated.

(cherry picked from commit 7ec44cd34c8b566fb581e0c64ec17570d4f2f658)
Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Idd90947d8d20ed5c59312d0ed84eea1f9c057265