exfat: series of problematic changes
Revert "exfat: fix appending discontinuous clusters to empty file"
This reverts commit 21313279887dba506b42eeb55a8e497d69efa17d.

Revert "exfat: changes the minimum supported kernel version from 4.10 to 5.15"
This reverts commit 47ed74ded6a1519c2f65a8c8cf347d98d4db1e84.

Log:
../fs/exfat/namei.c:1491:13: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, umode_t, bool)' (aka 'int (*)(struct inode *, struct dentry *, unsigned short, _Bool)') with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, umode_t, bool)' (aka 'int (struct user_namespace *, struct inode *, struct dentry *, unsigned short, _Bool)') [-Wincompatible-function-pointer-types]
 1491 |         .create         = exfat_create,
      |                           ^~~~~~~~~~~~
../fs/exfat/namei.c:1494:12: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, umode_t)' (aka 'int (*)(struct inode *, struct dentry *, unsigned short)') with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, umode_t)' (aka 'int (struct user_namespace *, struct inode *, struct dentry *, unsigned short)') [-Wincompatible-function-pointer-types]
 1494 |         .mkdir          = exfat_mkdir,
      |                           ^~~~~~~~~~~
../fs/exfat/namei.c:1496:13: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)' with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)' [-Wincompatible-function-pointer-types]
 1496 |         .rename         = exfat_rename,
      |                           ^~~~~~~~~~~~
../fs/exfat/namei.c:1497:13: error: incompatible function pointer types initializing 'int (*)(struct dentry *, struct iattr *)' with an expression of type 'int (struct user_namespace *, struct dentry *, struct iattr *)' [-Wincompatible-function-pointer-types]
 1497 |         .setattr        = exfat_setattr,
      |                           ^~~~~~~~~~~~~
../fs/exfat/namei.c:1498:13: error: incompatible function pointer types initializing 'int (*)(const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (*)(const struct path *, struct kstat *, unsigned int, unsigned int)') with an expression of type 'int (struct user_namespace *, const struct path *, struct kstat *, unsigned int, unsigned int)' [-Wincompatible-function-pointer-types]
 1498 |         .../fs/exfat/inode.c:366:36: warning: declaration of 'struct readahead_control' will not be visible outside of this function [-Wvisibility]
  366 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
getattr        = exfat_getattr,
      |                           ^~~~~~~~~~~~~
5 errors generated.
make[3]: *** [../scripts/Makefile.build:288: fs/exfat/namei.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      arch/arm64/kernel/io.o
../fs/exfat/inode.c:368:2: error: implicit declaration of function 'mpage_readahead' [-Werror,-Wimplicit-function-declaration]
  368 |         mpage_readahead(rac, exfat_get_block);
      |         ^
../fs/exfat/inode.c:538:3: error: field designator 'readahead' does not refer to any field in type 'const struct address_space_operations'
  538 |         .readahead      = exfat_readahead,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.

Conflicts:
    fs\exfat\dir.c
    fs\exfat\super.c

Revert "exfat: free the sbi and iocharset in ->kill_sb"
This reverts commit 8269c2d7f032cdc59295a14d3418bda40be7c573.

Log:
../fs/exfat/super.c:1115:9: error: implicit declaration of function 'exfat_free_sbi'; did you mean 'exfat_free_inode'? [-Werror=implicit-function-declaration]
 1115 |         exfat_free_sbi(sbi);
      |         ^~~~~~~~~~~~~~
      |         exfat_free_inode

Revert "exfat: move freeing sbi, upcase table and dropping nls into rcu-delayed helper"
This reverts commit 7ef5cda2349988f5869384929e3ff5162f406bc2.

Revert "exfat: Convert to new uid/gid option parsing helpers"
This reverts commit 05b27be3f86568266374a47feb05d7cce50905e5.

Revert "exfat: handle idmapped mounts"
This reverts commit cf95d93111b3a7ffeeeeebdc2b9a5c5a94f436cd.

Revert "exfat: do not sync parent dir if just update timestamp"
This reverts commit 4de5c4e7983964a209de066ddacbb22c5292fc4c.

Revert "exfat: remove duplicate update parent dir"
This reverts commit f497981eb379a44d258b274f498a91d4d15f451f.

Revert "exfat: change to get file size from DataLength"
This reverts commit f9cc939cb063513fdf166aaa7a35aee2a76a50ed.

Log:
../fs/exfat/inode.c:469:36: warning: declaration of 'struct readahead_control' will not be visible outside of this function [-Wvisibility]
  469 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
../fs/exfat/inode.c:471:37: error: incomplete definition of type 'struct readahead_control'
  471 |         struct address_space *mapping = rac->mapping;
      |                                         ~~~^
../fs/exfat/inode.c:469:36: note: forward declaration of 'struct readahead_control'
  469 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
../fs/exfat/inode.c:474:15: error: implicit declaration of function 'readahead_pos' [-Werror,-Wimplicit-function-declaration]
  474 |         loff_t pos = readahead_pos(rac);
      |                      ^
../fs/exfat/inode.c:479:29: error: implicit declaration of function 'readahead_length' [-Werror,-Wimplicit-function-declaration]
  479 |             ei->valid_size < pos + readahead_length(rac))
      |                                    ^
  CC      kernel/irq/dummychip.o
../fs/exfat/inode.c:482:2: error: implicit declaration of function 'mpage_readahead' [-Werror,-Wimplicit-function-declaration]
  482 |         mpage_readahead(rac, exfat_get_block);
      |         ^
  CC      drivers/base/power/generic_ops.o
../fs/exfat/inode.c:669:3: error: field designator 'readahead' does not refer to any field in type 'const struct address_space_operations'
  669 |         .readahead      = exfat_readahead,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 5 errors generated.

Revert "exfat: do not zero the extended part"
This reverts commit 7a111ad8de749bf68571932518f2d99a3a9198d8.

Revert "exfat: drop ->i_size_ondisk"
This reverts commit f203d46b70237e1ed7b937d562a9ad1f57dab034.

Revert "exfat: do not fallback to buffered write"
This reverts commit dc7c0b4568f65efca0d098cbd5623652654824ef.

Revert "exfat: fix timing of synchronizing bitmap and inode"
This reverts commit 15be380f969f60d8638c0dbbb3af3ab42256d25e.

Revert "exfat: fix zero the unwritten part for dio read"
This reverts commit b918344448212b43466dd74a6c24cefb9375a05c.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: d644e6c66ae7c5a594727850ccd8fc7128639442