Revert "soc: qcom: llcc cleanup to get rid of sdm845 specific driver file"
This reverts commit 077010717b52f8a5384470071408659e0894277e.

Log:
../drivers/soc/qcom/llcc-lahaina.c:77:9: error: implicit declaration of function 'qcom_llcc_probe' [-Werror,-Wimplicit-function-declaration]
   77 |         return qcom_llcc_probe(pdev, lahaina_data,
      |                ^
1 error generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I5a4df7c7de8e8587b7fc69d39c74485fea80a857