Revert "disp: msm: sde: Remove pm vote at time of handoff"
This reverts commit ea245e7982147e234773528e78f64db2135fb846.

Fix build.

Log:
../techpack/display/msm/sde/sde_kms.c: In function '_sde_kms_scm_call':
../include/linux/kern_levels.h:5:25: warning: format '%lld' expects argument of type 'long long int', but argument 4 has type 'int' [-Wformat=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
../include/linux/printk.h:143:24: note: in definition of macro 'no_printk'
  143 |                 printk(fmt, ##__VA_ARGS__);             \
      |                        ^~~
../include/linux/kern_levels.h:15:25: note: in expansion of macro 'KERN_SOH'
   15 | #define KERN_DEBUG      KERN_SOH "7"    /* debug-level messages */
      |                         ^~~~~~~~
../include/linux/printk.h:345:19: note: in expansion of macro 'KERN_DEBUG'
  345 |         no_printk(KERN_DEBUG pr_fmt(fmt), ##__VA_ARGS__)
      |                   ^~~~~~~~~~
../techpack/display/msm/sde/sde_kms.h:67:29: note: in expansion of macro 'pr_debug'
   67 | #define SDE_ERROR(fmt, ...) pr_debug("[sde error]" fmt, ##__VA_ARGS__)
      |                             ^~~~~~~~
../techpack/display/msm/sde/sde_kms.c:389:17: note: in expansion of macro 'SDE_ERROR'
  389 |                 SDE_ERROR("Error:scm_call2, vmid %lld, ret%d\n",
      |                 ^~~~~~~~~
../techpack/display/msm/sde/sde_kms.c: In function '_sde_kms_release_splash_resource':
../techpack/display/msm/sde/sde_kms.c:1272:54: error: expected expression before 'phandle'
 1272 |                         sde_power_data_bus_set_quota(phandle, i,
      |                                                      ^~~~~~~
../techpack/display/msm/sde/sde_kms.c:1272:25: error: too few arguments to function 'sde_power_data_bus_set_quota'
 1272 |                         sde_power_data_bus_set_quota(phandle, i,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ib733c1609903c0614605bedb4576e362e864e84f