Revert "bitmap: introduce generic optimized bitmap_size()"
This reverts commit 463074c08128271608da12cfcdd85b1d99412e81.

Log:
../include/linux/bitmap.h:219:62: error: expected ')' before '/' token
  219 | #define bitmap_size(nbits)      (ALIGN(nbits, BITS_PER_LONG) / BITS_PER_BYTE)
      |                                                              ^

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I20422532ba038757c5d3511ae73ff8870cc89cf3