Revert "ip_tunnels: use DEV_STATS_INC()"
This reverts commit 62c363e6041c7884dc9f27574492a3c9e33845e1.

Fix build.

Log:
../include/net/ip_tunnels.h: In function 'iptunnel_xmit_stats':
../include/net/ip_tunnels.h:459:17: error: implicit declaration of function 'DEV_STATS_INC' [-Werror=implicit-function-declaration]
  459 |                 DEV_STATS_INC(dev, tx_errors);
      |                 ^~~~~~~~~~~~~
In file included from ../include/net/dst_metadata.h:6,
                 from ../net/ipv4/route.c:91:

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I8203ab57f62905663c9fe48b65d955b216cb6c39