Revert "exfat: changes the minimum supported kernel version from 4.10 to 5.15"
This reverts commit 47ed74ded6a1519c2f65a8c8cf347d98d4db1e84.

Log:
../fs/exfat/namei.c:1491:13: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, umode_t, bool)' (aka 'int (*)(struct inode *, struct dentry *, unsigned short, _Bool)') with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, umode_t, bool)' (aka 'int (struct user_namespace *, struct inode *, struct dentry *, unsigned short, _Bool)') [-Wincompatible-function-pointer-types]
 1491 |         .create         = exfat_create,
      |                           ^~~~~~~~~~~~
../fs/exfat/namei.c:1494:12: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, umode_t)' (aka 'int (*)(struct inode *, struct dentry *, unsigned short)') with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, umode_t)' (aka 'int (struct user_namespace *, struct inode *, struct dentry *, unsigned short)') [-Wincompatible-function-pointer-types]
 1494 |         .mkdir          = exfat_mkdir,
      |                           ^~~~~~~~~~~
../fs/exfat/namei.c:1496:13: error: incompatible function pointer types initializing 'int (*)(struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)' with an expression of type 'int (struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)' [-Wincompatible-function-pointer-types]
 1496 |         .rename         = exfat_rename,
      |                           ^~~~~~~~~~~~
../fs/exfat/namei.c:1497:13: error: incompatible function pointer types initializing 'int (*)(struct dentry *, struct iattr *)' with an expression of type 'int (struct user_namespace *, struct dentry *, struct iattr *)' [-Wincompatible-function-pointer-types]
 1497 |         .setattr        = exfat_setattr,
      |                           ^~~~~~~~~~~~~
../fs/exfat/namei.c:1498:13: error: incompatible function pointer types initializing 'int (*)(const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (*)(const struct path *, struct kstat *, unsigned int, unsigned int)') with an expression of type 'int (struct user_namespace *, const struct path *, struct kstat *, unsigned int, unsigned int)' [-Wincompatible-function-pointer-types]
 1498 |         .../fs/exfat/inode.c:366:36: warning: declaration of 'struct readahead_control' will not be visible outside of this function [-Wvisibility]
  366 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
getattr        = exfat_getattr,
      |                           ^~~~~~~~~~~~~
5 errors generated.
make[3]: *** [../scripts/Makefile.build:288: fs/exfat/namei.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      arch/arm64/kernel/io.o
../fs/exfat/inode.c:368:2: error: implicit declaration of function 'mpage_readahead' [-Werror,-Wimplicit-function-declaration]
  368 |         mpage_readahead(rac, exfat_get_block);
      |         ^
../fs/exfat/inode.c:538:3: error: field designator 'readahead' does not refer to any field in type 'const struct address_space_operations'
  538 |         .readahead      = exfat_readahead,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.

Conflicts:
    fs\exfat\dir.c
    fs\exfat\super.c

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: 18b8f8d0ab3ef3cca203acb22c4813dfc654f77a